version: "3"
services:
  app:
    build:
      context: ./frontend
    restart: always
  # api:
  #   build:
  #     context: ./backend
  #   restart: always
  #   environment:
  #     - JSON_SERVER=http://jsonserver
  #   devices:
  #     - /dev/ttyACM0:/dev/ttyACM0
  #     - /dev/gpiomem:/dev/gpiomem
  #   volumes:
  #     - /sys:/sys
  #   depends_on:
  #     - "jsonserver"
  #   ports:
  #     - "3000:3000"
  jsonserver:
    build:
      context: ./docker-json-server
    restart: always
    volumes:
      - ./backend/db.json:/data/db.json
    ports:
      - "3080:80"
  restreamer:
    image: datarhei/restreamer-armv7l:latest
    restart: always
    environment:
      - RS_USERNAME=admin
      - RS_PASSWORD=iAmSuperSecure
      - RS_MODE=RASPICAM
    volumes:
      - /mnt/restreamer/db:/restreamer/db
      - /opt/vc:/opt/vc
    privileged: true
  nginx:
    image: nginx:1.16.0-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - restreamer
    depends_on:
      - "app"
      # - "api"
      - "restreamer"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  localtunnel:
    build:
      context: ./localtunnel
    restart: always
    depends_on:
      - nginx
    command:
      --local-host nginx --subdomain remote-sensebox --port 80
  localtunnel-restreamer:
    build:
      context: ./localtunnel
    restart: always
    depends_on:
      - nginx
    command:
      --local-host nginx --subdomain remote-sensebox-stream --port 8080
